version: "3.8"

services:
  web:
    container_name: deovr-json-gen
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # please copy .env.example to .env and update the values
      - .env
    ports:
      - "${WEB_PORT}:80"
    volumes:
      # please create a `deovr` file on root of this project if it doesn't exist
      - ./deovr:/usr/share/nginx/html/deovr
      - ${DEOVR_JSON_GEN_DIR}:/usr/share/nginx/html
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
